-- Add some sample venues to demonstrate the platform
-- Note: You'll need to replace the owner_id with actual user IDs from your auth.users table

INSERT INTO public.venues (
  name, 
  description, 
  address, 
  hourly_rate, 
  capacity, 
  images, 
  amenities, 
  tags,
  latitude,
  longitude,
  contact_email,
  contact_phone,
  status,
  owner_id
) VALUES 
(
  'Urban Studio Loft',
  'Modern industrial space perfect for creative events, workshops, and collaborative sessions. Features exposed brick walls, high ceilings, and state-of-the-art lighting.',
  '123 Creative District, Downtown, Melbourne VIC 3000',
  150,
  50,
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop'],
  ARRAY['WiFi', 'Sound System', 'Parking', 'Kitchen', 'Air Conditioning'],
  ARRAY['Studio', 'Creative', 'Workshop'],
  -37.8136,
  144.9631,
  'contact@urbanstudio.com',
  '+61 3 9000 1234',
  'active',
  (SELECT id FROM auth.users LIMIT 1) -- This will use the first user as owner
),
(
  'Rooftop Garden Venue',
  'Stunning rooftop space with panoramic city views and beautiful garden atmosphere. Perfect for networking events, product launches, and sophisticated gatherings.',
  '456 Sky Tower, Midtown Heights, Melbourne VIC 3141',
  280,
  100,
  ARRAY['https://images.unsplash.com/photo-1464207687429-7505649dae38?w=800&h=600&fit=crop'],
  ARRAY['WiFi', 'Bar', 'Outdoor Space', 'City Views', 'Catering Kitchen'],
  ARRAY['Rooftop', 'Networking', 'Corporate'],
  -37.8200,
  144.9700,
  'events@rooftopgarden.com',
  '+61 3 9000 5678',
  'active',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Tech Conference Hall',
  'Professional conference space equipped with cutting-edge technology and flexible seating arrangements. Ideal for tech talks, product demos, and large presentations.',
  '789 Innovation Hub, Business District, Melbourne VIC 3000',
  400,
  200,
  ARRAY['https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=600&fit=crop'],
  ARRAY['WiFi', 'AV Equipment', 'Parking', 'Coffee Station', 'Security'],
  ARRAY['Conference', 'Tech', 'Corporate'],
  -37.8100,
  144.9600,
  'bookings@techconferencehall.com',
  '+61 3 9000 9012',
  'active',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Warehouse Event Space',
  'Raw industrial warehouse perfect for unique events, art exhibitions, and large gatherings. Flexible space that can be customized for any type of event.',
  '321 Industrial Ave, Port Melbourne VIC 3207',
  180,
  300,
  ARRAY['https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&h=600&fit=crop'],
  ARRAY['WiFi', 'Parking', 'Kitchen', 'Sound System'],
  ARRAY['Warehouse', 'Exhibition', 'Large Events'],
  -37.8400,
  144.9300,
  'hello@warehousevenue.com',
  '+61 3 9000 3456',
  'active',
  (SELECT id FROM auth.users LIMIT 1)
),
(
  'Boutique Meeting Room',
  'Intimate and elegant meeting space perfect for board meetings, client presentations, and small team collaborations. Premium furnishings and professional atmosphere.',
  '654 Business Plaza, South Yarra VIC 3141',
  120,
  20,
  ARRAY['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=600&fit=crop'],
  ARRAY['WiFi', 'AV Equipment', 'Coffee Station', 'Air Conditioning'],
  ARRAY['Meeting Room', 'Corporate', 'Small Groups'],
  -37.8300,
  144.9900,
  'bookings@boutiquemeeting.com',
  '+61 3 9000 7890',
  'active',
  (SELECT id FROM auth.users LIMIT 1)
);