name: Kolab CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (npm/pnpm/yarn)
        run: |
          if [ -f package-lock.json ]; then npm ci; \
          elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
          elif [ -f yarn.lock ]; then npm i -g yarn && yarn --frozen-lockfile; \
          else npm i; fi

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Typecheck (if present)
        run: npm run typecheck --if-present || npx tsc --noEmit || true

      - name: Build (fallback to vite)
        run: npm run build --if-present || npx vite build
        env:
          CI: true
